<a href="https://colab.research.google.com/github/Nomad653/Python/blob/main/Deep%20learning/AAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import tensorflow as tf

In [9]:
import pandas as pd


In [10]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")

In [15]:
X = data.iloc[:,3:-1].values

In [17]:
y = data.iloc[:,-1].values

In [18]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [19]:
from sklearn.preprocessing import LabelEncoder

In [23]:
le = LabelEncoder()

In [24]:
X[:,2] = le.fit_transform(X[:,2])

In [25]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [26]:
from sklearn.compose import ColumnTransformer

In [30]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [32]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[1])],remainder="passthrough")

In [33]:
X = np.array(ct.fit_transform(X))

In [36]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [37]:
from sklearn.model_selection import train_test_split

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [40]:
from sklearn.preprocessing import StandardScaler

In [41]:
sc = StandardScaler()

In [42]:
X_train = sc.fit_transform(X_train)

In [43]:
X_test = sc.fit_transform(X_test)