<a href="https://colab.research.google.com/github/Nomad653/Python/blob/main/Deep%20learning/AAN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### **Importing libraries**

In [9]:
import tensorflow as tf
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [10]:
data = pd.read_csv("/content/drive/MyDrive/Machine Learning A-Z (Codes and Datasets)/Part 8 - Deep Learning/Section 39 - Artificial Neural Networks (ANN)/Python/Churn_Modelling.csv")

In [15]:
X = data.iloc[:,3:-1].values

In [17]:
y = data.iloc[:,-1].values

In [18]:
y

array([1, 0, 1, ..., 1, 1, 0])

In [23]:
le = LabelEncoder()

In [24]:
X[:,2] = le.fit_transform(X[:,2])

In [32]:
ct = ColumnTransformer(transformers = [("encoder",OneHotEncoder(),[1])],remainder="passthrough")

In [33]:
X = np.array(ct.fit_transform(X))

In [39]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [41]:
sc = StandardScaler()

In [42]:
X_train = sc.fit_transform(X_train)

In [43]:
X_test = sc.fit_transform(X_test)

## **Initializing the AAN**

In [46]:
ann = tf.keras.models.Sequential()

Adding the input layer

In [47]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# **Adding the second layer** 

In [48]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

##**Adding the output layer**

In [49]:
ann.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

### **Compiling the model**

In [50]:
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=['accuracy'])

In [51]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 4ms/step - loss: 0.5597 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4821 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4539 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4394 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4313 - accuracy: 0.7965
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4253 - accuracy: 0.8021
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4197 - accuracy: 0.8098
Epoch 8/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4141 - accuracy: 0.8174
Epoch 9/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4090 - accuracy: 0.8200
Epoch 10/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4042 - accura

In [58]:
ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))

array([[0.0782173]], dtype=float32)

array([[1.]], dtype=float32)